version: "3.9"

services:
  app:
    build: .
    container_name: llm_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - llm-net

  redis:
    image: redis:7
    container_name: llm_redis
    ports:
      - "6379:6379"
    networks:
      - llm-net

networks:
  llm-net:
    external: true